spring:
  thymeleaf:
    enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
custom:
  naver:
    clientId: 'CLIENT ID'
    secret-key: 'SECRET-KEY'
  kakao:
    clientId: 'CLIENT ID'
  toss_payment:
    secretKey: 'SECRET KEY'
  mail:
    username: 'EMAIL'
    password: 'EMAIL KEY'
  amazonS3:
    end-point: 'https://end.point/'
    region-name: 'REGION NAME'
    access-key: 'ACCESS KEY'
    secret-key: 'SECRET KEY'
    cdn-end-point: 'http://end.point/'
    bucket-name: 'BUCKET NAME'
  api:
    business-register-number: 'SECRET KEY'
    nutrient-business-register-number: 'SECRET KEY'